spring:
  application:
    name: easy-poi1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://39.105.125.176:3306/halm_atn?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    max-active: 200
    max-wait: 60000
    min-idle: 10
    hikari:
      minimum-idle: 1
  redis:
    host: ${REDIS_DEFAULT_URL:127.0.0.1}
    port: 6379
    database: 1
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB

mybatis:
  mapperLocations:
    - classpath*:/mapper/*Mapper.xml
    - classpath*:/mapper/*/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

minio:
  url: http://39.105.125.176:9000
  access-key: mist
  secret-key: mist2mist

